//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gdfglfdjglfdkgfd.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("gdfglfdjglfdkgfd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to II
        ///1
        ///III
        ///2
        ///IV
        ///3
        ///VI
        ///4
        ///VII
        ///5
        ///VIII
        ///6
        ///XI
        ///7
        ///XII
        ///8
        ///XIII
        ///9
        ///XIV
        ///0
        ///XIX
        ///$
        ///XV
        ///a
        ///b
        ///c
        ///d
        ///e
        ///f
        ///g
        ///h
        ///i
        ///j
        ///k
        ///l
        ///m
        ///n
        ///o
        ///p
        ///q
        ///r
        ///s
        ///t
        ///u
        ///v
        ///w
        ///x
        ///y
        ///z
        ///XVI
        ///XVII
        ///XVIII
        ///XX
        ///XXI
        ///XXII
        ///XXIII
        ///XXIV
        ///XXIX
        ///XXV
        ///XXVI
        ///XXVII
        ///XXVIII
        ///XXX
        ///XXXI
        ///XXXII
        ///XXXIII
        ///XXXIV
        ///XXXIX
        ///XXXV
        ///XXXVI
        ///XXXVII
        ///XXXVIII
        ///a                                   
        ///adieu                               
        ///afin                                
        ///ah                                  
        ///ai                                  
        ///aie    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
    }
}
